accounts/urls.py
from django.urls import path

from .views import create_user, login_user, logout_view

app_name = 'accounts'

urlpatterns = [
    path('creation/', create_user, name='create'),
    path('login/', login_user, name='login'),
    path('logout/', logout_view, name='logout'),
]

articles/urls.py
from django.urls import path

from .views import list_article, formulaire, get_and_update, add_comment
from .view_class import ArticleListView, ArticleCreateView, ArticleDetailView

# app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='list-articles'),
    path('class/', ArticleListView.as_view(), name='list-articles-class'),
    path('ajout/', formulaire, name='form-articles'),
    path('ajout-class/', ArticleCreateView.as_view(), name='form-articles-class'),
    path('edit/<int:id>/', get_and_update, name='edit'),
    path('detail/<int:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('add-comment/<int:id>/', add_comment, name='add-comment'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# titre, contenu, date publication, resume


class Article(models.Model):

    title = models.CharField(max_length=255, verbose_name='titre')
    sumary = models.CharField(max_length=255, null=True, blank=True, verbose_name='resume')
    content = models.TextField(verbose_name='contenu')
    date_pub = models.DateField(null=True, verbose_name='date de publication', default=timezone.now)
    cover = models.ImageField(upload_to='articles', max_length=255, null=True, verbose_name="photo de couverture")
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=False)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField(verbose_name='contenu')
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=False)

    def __str__(self):
        return f"{self.created_at}"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class UserLoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=50, min_length=3, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(required=True, max_length=50, min_length=3, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

articles/forms.py
from django import forms

from .models import Article, Comment


# class ArticleForm(forms.Form):
#     title = forms.CharField(min_length=2, max_length=255)
#     sumary = forms.CharField(min_length=2, max_length=255, required=False)
#     date_pub = forms.DateField(required=False, widget=forms.DateInput())
#     content = forms.CharField(widget=forms.Textarea(attrs={'required': True}))

class ArticleForm(forms.ModelForm):

    # tag = forms.CharField(max_length=240, min_length=2, required=True,
    #                       widget=forms.TextInput(attrs={'class': 'form-control'}))
    

    class Meta:
        model = Article
        fields = ('title', 'sumary', 'cover', 'date_pub', 'content')
        widgets = {
            "content": forms.Textarea(attrs={"cols": 80, "rows": 20}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'sumary': forms.TextInput(attrs={'class': 'form-control'}),
            'date_pub': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect


from .forms import UserForm, UserLoginForm


def create_user(request):
    if request.user.is_authenticated:
        return redirect('list-articles-class')
    if request.method == 'GET':
        form = UserForm()
    elif request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = User.objects.create_user(
                username=cleaned_data.get('username'),
                email=cleaned_data.get('email'),
                password=cleaned_data.get('password')
            )
            user.first_name = cleaned_data.get('first_name')
            user.last_name = cleaned_data.get('last_name')
            user.save()
            return redirect('list-articles-class')
    data = {
        'form': form
    }
    return render(
        context=data, request=request, template_name='accounts/creation.html'
        )


def login_user(request):
    if request.user.is_authenticated:
        return redirect('list-articles-class')
    if request.method == "GET":
        form = UserLoginForm()
    elif request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(
                request=request, username=username, password=password
                )
            if user is not None:
                login(request=request, user=user)
                return redirect('list-articles-class')

    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('accounts:login')

articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import ArticleForm, CommentForm
from .models import Article


def list_article(request):
    arts = Article.objects.all()
    context = {
        'articles': arts
    }
    return render(request, 'articles/list-articles.html', context)


@login_required  # decorateur
def formulaire(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, files=request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()  # enregistrement dans la base
            return redirect(reverse('list-articles'))
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/formulaire.html', context)

@login_required
def get_and_update(request, id):
    article = Article.objects.get(id=id)  # recuperation d'un article
    if request.method == 'GET':
        form = ArticleForm(instance=article)  # creation d'un formulaire
    elif request.method == 'POST':
        form = ArticleForm(instance=article, data=request.POST, files=request.FILES)  # creation d'un formulaire
        if form.is_valid():
            form.save()
            return redirect(reverse('list-articles'))
    context = {
        'article': article,
        'form': form
    }
    return render(request, 'articles/edit.html', context)


def add_comment(request, id):

    if request.method == 'POST':
        article = Article.objects.get(id=id)
        # initial = {'article': article}
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.owner = request.user
            comment.save()
        else:
            context = {
                'article': article,
                'form': form
            }
            return render(request, 'articles/article_detail.html', context)
    return redirect('detail', article.id)

accounts/templates/accounts/creation.html
{% extends "articles/layout.html" %}
    
    {% block content %}
    <div class="row">
        <div class="col-6">
            <h1>Creation de compte</h1>
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                {{ field.label_tag }}
                    {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                                <li><strong style="color: red;">{{ error|escape }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
        
                     {{ field }}
                {% endfor %}
                
                <input type="submit" value="Enregistrer" class="btn btn-primary">
                <input type="reset" value="Annuler" class="btn btn-danger">
        
            </form>
            <div class="row">
                <p>
                    <a href="{% url 'accounts:login' %}">Se connecter</a>
                </p>
            </div>
        </div>
    </div>
   
    
    {% endblock content %}
    

accounts/templates/accounts/login.html
{% extends "articles/layout.html" %}
    
    {% block content %}
    <div class="row">
        <div class="col-6">
            <h1>Connexion</h1>
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                {{ field.label_tag }}
                    {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                                <li><strong style="color: red;">{{ error|escape }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
        
                     {{ field }}
                {% endfor %}
                
                <input type="submit" value="Connexion" class="btn btn-primary">
                <input type="reset" value="Annuler" class="btn btn-danger">
        
            </form>
            <div class="row">
                <p>
                    <a href="{% url 'accounts:create' %}">Creer un compte</a>
                </p>
            </div>
        </div>
    </div>
   
    
    {% endblock content %}
    

articles/templates/articles/article_detail.html
{% extends "articles/layout.html" %}
{% block content %}
    <h1>{{ article.title }}</h1>
    <div class="row">
        <div class="col-10 offset-1">
            <img style="width: 80%; height: 200px;" src="{% if article.cover %} {{ article.cover.url }} {% endif %}" class="card-img-top" alt="{{ article.title }}">
        </div>
    </div>
    <hr>
    <p>{{ article.user.get_full_name }}</p>
    {% if user.is_authenticated and user == article.user %}
        <a class="btn btn-warning" href="{% url 'edit' article.id %}"> Modifier l'article</a>
    {% endif %}
    <hr>
    <div class="row">
        <div class="col-10 offset-1">
            {{ article.content }}
        </div>
    </div>
    <hr>
    {% for comment in article.comment_set.all %}
    <div class="row">
        <div class="col-3">
            <div class="card text-bg-light mb-3" style="max-width: 18rem;">
                <div class="card-header">{{ comment.owner.get_full_name }}</div>
                <div class="card-body">
                  <h5 class="card-title">{{ comment.created_at }}</h5>
                  <p class="card-text">{{ comment.content }}</p>
                </div>
              </div>              
        </div>
    </div>
    
    {% endfor %}
    {% if user.is_authenticated %}
        <form action="{% url 'add-comment' article.id %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-10 offset-1">
                    <table>
                        {{ form }}
                    </table>
                </div>
                <p>
                    <button class="btn btn-primary">Enregistrer</button>
                </p>
            </div>

        </form>
    {% endif %}
    
   

{% endblock content %}

articles/templates/articles/article_list.html
{% extends "articles/layout.html" %}
{% block content %}
    <h1>Liste </h1>
    <a href="{% url "form-articles" %}">Ajouter</a>
    <div class="row">
        
        {% for article  in articles %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{% if article.cover %} {{ article.cover.url }} {% endif %}" class="card-img-top" alt="{{ article.title }}">
                <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.sumary }}</p>
                <a href="{% url 'detail' article.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
      {% endfor %}

    </div>
    

{% endblock content %}
   

articles/templates/articles/edit.html
{% extends "articles/layout.html" %}
    
    {% block content %}
    <h1>Formulaire de modification des articles</h1>
    <a href="{% url 'list-articles' %}">Retour</a>
    <form action="{% url 'edit' article.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% for field in form %}
        {{ field.label_tag }}
            {% if field.errors %}
                <ul>
                    {% for error in field.errors %}
                        <li><strong style="color: red;">{{ error|escape }}</strong></li>
                    {% endfor %}
                </ul>
            {% endif %}

             {{ field }}
        {% endfor %}
        <div class="row">
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary">Enregistrer</button>
            </div>
            <div class="col-md-1">
                <button type="reset" class="btn btn-danger">Annuler</button>
            </div>
        </div>
       

    </form>
    
    {% endblock content %}
    

articles/templates/articles/formulaire.html
{% extends "articles/layout.html" %}
    
    {% block content %}
    <h1>Formulaire de creation des articles</h1>
    <a href="{% url 'list-articles' %}">Retour</a>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        {{ field.label_tag }}
            {% if field.errors %}
                <ul>
                    {% for error in field.errors %}
                        <li><strong style="color: red;">{{ error|escape }}</strong></li>
                    {% endfor %}
                </ul>
            {% endif %}

             {{ field }}
        {% endfor %}
        
        <input type="submit" value="Enregistrer" class="btn btn-primary">
        <input type="reset" value="Annuler" class="btn btn-danger">

    </form>
    
    {% endblock content %}
    

articles/templates/articles/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'articles/bootstrap.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Articles</title>
</head>
<body>
    <div class="container">
        {% include "articles/navbar.html" %}

        {% block content %}
        {% endblock content %}
    </div>
    

    
</body>
</html>

articles/templates/articles/list-articles.html
{% extends "articles/layout.html" %}
{% block content %}
    <h1>Liste des articles</h1>
    <a href="{% url "form-articles" %}">Ajouter</a>
    <table class="table table-striped ">
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Couverture</th>
            <th>Resume</th>
        </tr>
        {% for article  in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td> {% if article.cover %}
                        <img src="{{ article.cover.url }}" alt="">
                    {% endif %}
                </td>
                <td>{{ article.sumary }}</td>
            </tr>
        {% endfor %}
        
    </table>


{% endblock content %}
   

articles/templates/articles/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Accueil</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url "list-articles" %}">Liste</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "form-articles" %}">Ajouter</a>
            </li>
          {% endif %}
          
          {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:login" %}">Connexion</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:logout" %}">Deconnexion</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>